kind: Pod
apiVersion: v1
metadata:
  name: hostpath-provisioner
spec:
  containers:
    - name: hostpath-provisioner
      image: 9rga/k8s-hostpath-provisioner:latest
      imagePullPolicy: "Always"
      env:
        - name: PV_BASEPATH
          value: "/home/eth/www/pv"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
  serviceAccountName: 9rga-hostpath-provisioner
